### ISSUE TITLE
Heuristic baseline

### ISSUE THREAD

**Issue by chenkins** [flatland-association/flatland-rl#101]
**Objectives**
Provide heuristic baseline

**Todos**
* [ ] Cleanup code https://github.com/flatland-association/flatland-benchmarks-f3-deadlock-avoidance-baseline, make it re-usable
* [ ] Documentation in flatland-book
* [ ] Use as example for #75 

**Minimal testing requirements**

**Additional context**
