### ISSUE TITLE
Reproducability: Random Number Generation 

### ISSUE THREAD

**Issue by aiAdrian** [flatland-association/flatland-rl#18]
### Objectives
This issue aims to fulfill the following objectives:
- Ensure that we can set a random number seed and it will be used for the complete experiment -> reproducability

### Todos
What needs to be done for the issue to be done and the objectives to be reached:
- [x] Check all random number generation usage (ensure only one random number generation library is used)
- [x] Check whether the random seed is just once set 
- [x] Fix the issue so that the RailEnv, RailEnvGenerator, ...  generates for each run the same scenario -> reproducability / deterministic runtime 

### Minimal testing requirements
What functionality shall be covered by a test (qualitatively describe each test):
- [ ] Reviewed and fix
