### ISSUE TITLE
DummyObservationBuilder fix

### ISSUE THREAD

**Issue by aiAdrian** [flatland-association/flatland-rl#23]
The DummyObservationBuilder returns true instead of a List: get_many

### Objectives
`  class DummyObservationBuilder(ObservationBuilder):
    

    def __init__(self):
        super().__init__()

    def reset(self):
        pass

    def get_many(self, handles: Optional[List[int]] = None) -> bool:
        return True

    def get(self, handle: int = 0) -> bool:
        return True`

- ...

### Todos
- [ ] Check where the DummyObservationBuilder is used in Flatland
- [ ] Correct the get method, that for each Agent a List (np.array) is returned 
- [x] Correct the get_many method, such as it returns a list of [ get ( ...) , ... ] for each agent one observation

### Minimal testing requirements
- [ ] Test the use of DummyObservationBuilder  is all found Flatland parts 
- [x] Write a unit test
