### ISSUE TITLE
Remove the dependencies to Gym

### ISSUE THREAD

**Issue by aiAdrian** [flatland-association/flatland-rl#26]
### Objectives
In the codebase of Flatland there are gym dependencies, but they should be removed since there is not much functionality used. In some parts there are only imports, without using the imported functionality. 

### Todos
What needs to be done for the issue to be done and the objectives to be reached:
- [ ] Gym imports are removed
- [ ] Gym depandency is removed in setup.py / requirements_xxxx.txt 

### Minimal testing requirements
- [ ] Flatland behaves similarly to how it did before the gym was removed
