### ISSUE TITLE
Performance issue: Agent_chains.py (find_conflicts)

### ISSUE THREAD

**Issue by aiAdrian** [flatland-association/flatland-rl#6]
A major bottleneck was found in agent_chains.py when profiling the performance profiles:
- 50% of the calculation time in the step function is used by agent_chains.py (find-conflics)
- agent-chain.py is using **networkx**  - if networkX is too slow, it could at best be replaced by a faster library - see  (https://www.timlrx.com/blog/benchmark-of-popular-graph-network-packages / https://graph-tool.skewed.de/performance) 

https://github.com/flatland-association/flatland-rl/blob/main/flatland/envs/agent_chains.py 

Doc: Unordered Close Following (UCF) https://flatland.aicrowd.com/environment/Agent-Close-Following.html

![image](https://user-images.githubusercontent.com/10423646/230480916-f6499869-4e79-4f7e-9eda-2d7596ca5aea.png)

https://jiffyclub.github.io/snakeviz/

### Objectives
- [ ]  analysis of performance and identification of methods that improve the performance

### Todos

- [ ] Performance analysis needs to be done in detail - small and large flatland scenarios with 1 to many agents must be tested.

- [ ] The methods for finding conflicts should be analyzed - can it be reformulated to achieve faster computation time?
- [ ] Clarification of the reason why this method is needed - what does this method really do?
- [ ] After clarifing the bottleneck - the implementation steps must be defined and described in a new issue.

### Minimal testing requirements
- The findings are discussed in the dev tech meeting and the core team understands why this feature is required. And how it could improved with respect to the performance. The implementation steps are cleared. It should be ready for coding after the discussion.

**Comment by chenkins** [comment]
Relates  to #86

**Comment by chenkins** [comment]
Update from @aiAdrian 
```
class RailEnvironment(Environment):

    def __init__(self,
                 obs_builder_object: ObservationBuilder,
                 max_rails_between_cities=2,
                 max_rails_in_city=4,
                 malfunction_rate=1 / 1000,
                 n_cities=5,
                 number_of_agents=10,
                 grid_width=30,
                 grid_height=40,
                 grid_mode=True,
                 random_seed=25041978,
                 silent=False):



env = RailEnvironment(obs_builder_object=observation_builder, number_of_agents=100)

Motion Check / Agents chain
```

> 100 agents => 34%
> Ist gar nicht mehr so viel – wie es mal war 😊

**Comment by gdalle** [comment]
FYI I worked on this with an intern @bcrobin03, there must still be a branch somewhere with a much simpler motion check algorithm

**Comment by chenkins** [comment]
@gdalle @bcrobin03 👍 would be interested if you can find it.

**Comment by gdalle** [comment]
The branch is probably this one: https://github.com/bcrobin03/flatland-rl/commit/07de3f1d26d2490cc471294bacee95e13a85e686 (but I'm still trying to get in touch with Robin).

It relies on a very simple algorithm which doesn't require the existing color-based scheme. I would be happy to hop on a call and explain it to you one of these days.
