### ISSUE TITLE
enable a redis container in github workflow and configure test_service.ipynb to use it

### ISSUE THREAD

**Issue by hagrid67** [flatland-association/flatland-rl#65]
**Objectives**
Re-enable `test_service.ipynb` in `tox notebooks` to test the evaluation service

**Todos**
- [x] enable a `redis` container for the notebooks workflow
- [x] pass the redis container host(?) to the notebook in an environment variable `redis_ip`
- [x] uncomment the `test_service.ipynb`

**Minimal testing requirements**
N/A - this change enables an existing test to run

**Additional context**
`checks.yml` notebooks have recently been enabled by Jeremy / @hagrid67 in PR #61 
@fnberta would you mind taking a look at enabling `redis` in the workflow please?  (Or I'll take a look in a few days)

**Comment by fnberta** [comment]
Yes, I can look into it. But do we really want to require a redis instance to be running just to run the checks in our build pipeline?
