### ISSUE TITLE
Standardization of built-in observations

### ISSUE THREAD

**Issue by aiAdrian** [flatland-association/flatland-rl#7]
### Objectives
Flatland observations do not return a standardized vectorized representation. This makes exchanging policies quite complicated:
- All built-in observations return a "matrix" : n_agents x features_size by default

### Todos
Check all built-in observations with get(...) / get_many(...) :
- [ ] TreeObsForRailEnv is fixed 
- [ ] GlobalObsForRailEnv is fixed 
- [ ] LocalObsForRailEnv is fixed 
- [ ] DummyObservationBuilder is fixed 

### Minimal testing requirements
- [ ] A working example is implemented - interchangeable of observation (policy)
