### ISSUE TITLE
Cli/notebooks for (performance) evaluation

### ISSUE THREAD

**Issue by chenkins** [flatland-association/flatland-rl#78]
**Objectives**
First benchmark tooling. Further appetite will come with eating...

**Todos**
- [ ] Log current commit/git diff
- [ ] ability to run with cProfile
- [ ] cli/notebook for matrix training/evaluation (see #74), write logs of one "run" to folder and upload to S3
- [ ] cli/notebook for generating a matrix of results from one run (e.g. comparing average epoch time across different algorithms/policies)
- [ ] cli/notebook for comparing different results (e.g. timeline of average epoch times before and after a certain refactoring)

**Minimal testing requirements**
Think about what behavior shall be covered by a test (qualitatively describe each test).

**Additional context**
Preparation for #59 
Depends on #77 #74
