### ISSUE TITLE
Exchange solvers aka. policy abstraction

### ISSUE THREAD

**Issue by aiAdrian** [flatland-association/flatland-rl#8]
### Objectives
Different solvers (e.g. Policy) should be testable without changing the general Flatland.
- A general Flatland Problem Solver framework should be implemented 

### Todos
What needs to be done for the issue to be done and the objectives to be reached:
- [x] Flatland Problem Solver Generalisation has to be implemented 
- [x] Exchangebale learning Multi-Agent-Reinforcement-Policy and optimisation strategy must be implemement, such as DDDQN, PPO, ... 
- [x] Heuristic solvers (policy) have to be implemented to demostrate that Flatland is more than MARL

### Minimal testing requirements
Policy exchange capability can be demostrated 
- [x] A working examples is available

**Comment by chenkins** [comment]
Closed in #157
