### ISSUE TITLE
reinstate visual environment editor using working components

### ISSUE THREAD

**Issue by hagrid67** [flatland-association/flatland-rl#9]
### Objectives
This issue aims to fulfill the following objectives:
- replace the defunct `[jupyter_canvas_widget](https://github.com/Who8MyLunch/Jupyter_Canvas_Widget)` component with `ipycanvas`
- [dropping this objective] fix the visual editor so we can create and edit environments (ie rails / railenvs)
- [replacement objective] get some basic editor functionality working as a prototype of how this could be made to work again.
- should have a side effect of getting the `Agent-Close-Following.ipynb` notebook working

### Todos
What needs to be done for the issue to be done and the objectives to be reached:
- [x] take existing flatland/utils/editor.py, remove `import jpy_canvas`, introduce alternative `ipycanvas` widget
-- Previously (2-3y ago) there was a loss of functionality using `ipycanvas`; can't actually remember what it was.
- [x] get existing code `editor.py` `env_edit_utils.py` (sort of) working

These items can be moved to a new issue:
- TBD whether to introduce new features or improve behaviour at this stage:
-- eg adding new origins / destinations / trains 
-- time-stepping an environment in Jupyter (Lab and/or Notebook)
-- Run the editor in a `panel serve` setting (a more dashboard-like setting than notebook, without the same code editing ability.  Will make a new issue for this)

### Minimal testing requirements
What functionality shall be covered by a test (qualitatively describe each test):
- [x] existing `agent-close-following.ipynb` should run.  (Copy it from an earlier branch / checkpoint from before it was deleted)
- [ ] manual test: run `scene-editor.ipynb`, manually edit and save an environment

Creating a meaningful automated UI test may not be simple and will need to go in its own issue.  Suggest looking at [Playwright](https://playwright.dev/python/) as per Panel docs on [testing](https://panel.holoviz.org/developer_guide/testing.html)
